name: ci
permissions: read-all
on:
  push: null
  pull_request: null
  workflow_call: null # publish.yml runs this before releasing to npm
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: bun
        uses: oven-sh/setup-bun@v2
      - name: trunk
        uses: trunk-io/trunk-action@e1234e67a86010d61ddac8d8ebf4b783e2ffd2fa # v2.0.0
      - name: typecheck
        run: bun run lint:types
      - name: test
        run: bun run test
      - name: build
        run: bun run build
      - name: start
        run: bun run start:exec
